resilience4j:
  retry:
    instances:
      backendA:
        maxAttempts: 3
        waitDuration: 5s
        enableExponentialBackoff: false
  ratelimiter:
    instances:
      backendA:
        limit-for-period: 5
        limit-refresh-period: 10s
        timeout-duration: 0
  circuitbreaker:
    instances:
      circuit:
        sliding-window-size: 5
        failure-rate-threshold: 50
        permitted-number-of-calls-in-half-open-state: 5
        register-health-indicator: true
        event-consumer-buffer-size: 10
      